# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


puts 'SETTING UP DEFAULT USERS'
user = User.create :name => 'Elena', :surname => 'Burachevskaya', :email => 'example@example.com', :password => '123456', :password_confirmation => '123456', :confirmed_at => DateTime.now

puts 'SETTING UP COUNTRIES'

[
  { :title => 'Belarus', :iso_two_letter_code => 'BY' },
  { :title => 'Russia', :iso_two_letter_code => 'RU' },
  { :title => 'Ukraine', :iso_two_letter_code => 'UA' },
  { :title => 'United Kingdom', :iso_two_letter_code => 'GB' },
  { :title => 'United States', :iso_two_letter_code => 'US' },
  { :title => 'Afghanistan', :iso_two_letter_code => 'AF' },
  { :title => 'Aland Islands', :iso_two_letter_code => 'AX' },
  { :title => 'Albania', :iso_two_letter_code => 'AL' },
  { :title => 'Algeria', :iso_two_letter_code => 'DZ' },
  { :title => 'American Samoa', :iso_two_letter_code => 'AS' },
  { :title => 'Andorra', :iso_two_letter_code => 'AD' },
  { :title => 'Angola', :iso_two_letter_code => 'AO' },
  { :title => 'Anguilla', :iso_two_letter_code => 'AI' },
  { :title => 'Antarctica', :iso_two_letter_code => 'AQ' },
  { :title => 'Antigua And Barbuda', :iso_two_letter_code => 'AG' },
  { :title => 'Argentina', :iso_two_letter_code => 'AR' },
  { :title => 'Armenia', :iso_two_letter_code => 'AM' },
  { :title => 'Aruba', :iso_two_letter_code => 'AW' },
  { :title => 'Australia', :iso_two_letter_code => 'AU' },
  { :title => 'Austria', :iso_two_letter_code => 'AT' },
  { :title => 'Azerbaijan', :iso_two_letter_code => 'AZ' },
  { :title => 'Bahamas', :iso_two_letter_code => 'BS' },
  { :title => 'Bahrain', :iso_two_letter_code => 'BH' },
  { :title => 'Bangladesh', :iso_two_letter_code => 'BD' },
  { :title => 'Barbados', :iso_two_letter_code => 'BB' },
  { :title => 'Belgium', :iso_two_letter_code => 'BE' },
  { :title => 'Belize', :iso_two_letter_code => 'BZ' },
  { :title => 'Benin', :iso_two_letter_code => 'BJ' },
  { :title => 'Bermuda', :iso_two_letter_code => 'BM' },
  { :title => 'Bhutan', :iso_two_letter_code => 'BT' },
  { :title => 'Bolivia', :iso_two_letter_code => 'BO' },
  { :title => 'Bosnia and Herzegovina', :iso_two_letter_code => 'BA' },
  { :title => 'Botswana', :iso_two_letter_code => 'BW' },
  { :title => 'Bouvet Island', :iso_two_letter_code => 'BV' },
  { :title => 'Brazil', :iso_two_letter_code => 'BR' },
  { :title => 'British Indian Ocean Territory', :iso_two_letter_code => 'IO' },
  { :title => 'Brunei Darussalam', :iso_two_letter_code => 'BN' },
  { :title => 'Bulgaria', :iso_two_letter_code => 'BG' },
  { :title => 'Burkina Faso', :iso_two_letter_code => 'BF' },
  { :title => 'Burundi', :iso_two_letter_code => 'BI' },
  { :title => 'Cambodia', :iso_two_letter_code => 'KH' },
  { :title => 'Cameroon', :iso_two_letter_code => 'CM' },
  { :title => 'Canada', :iso_two_letter_code => 'CA' },
  { :title => 'Cape Verde', :iso_two_letter_code => 'CV' },
  { :title => 'Cayman Islands', :iso_two_letter_code => 'KY' },
  { :title => 'Central African Republic', :iso_two_letter_code => 'CF' },
  { :title => 'Chad', :iso_two_letter_code => 'TD' },
  { :title => 'Chile', :iso_two_letter_code => 'CL' },
  { :title => 'China', :iso_two_letter_code => 'CN' },
  { :title => 'Christmas Island', :iso_two_letter_code => 'CX' },
  { :title => 'Cocos (Keeling) Islands', :iso_two_letter_code => 'CC' },
  { :title => 'Colombia', :iso_two_letter_code => 'CO' },
  { :title => 'Comoros', :iso_two_letter_code => 'KM' },
  { :title => 'Congo', :iso_two_letter_code => 'CG' },
  { :title => 'Congo (DRC)', :iso_two_letter_code => 'CD' },
  { :title => 'Cook Islands', :iso_two_letter_code => 'CK' },
  { :title => 'Costa Rica', :iso_two_letter_code => 'CR' },
  { :title => 'Cote d\'Ivoire', :iso_two_letter_code => 'CI' },
  { :title => 'Croatia', :iso_two_letter_code => 'HR' },
  { :title => 'Cuba', :iso_two_letter_code => 'CU' },
  { :title => 'Cyprus', :iso_two_letter_code => 'CY' },
  { :title => 'Czech Republic', :iso_two_letter_code => 'CZ' },
  { :title => 'Denmark', :iso_two_letter_code => 'DK' },
  { :title => 'Djibouti', :iso_two_letter_code => 'DJ' },
  { :title => 'Dominica', :iso_two_letter_code => 'DM' },
  { :title => 'Dominican Republic', :iso_two_letter_code => 'DO' },
  { :title => 'Ecuador', :iso_two_letter_code => 'EC' },
  { :title => 'Egypt', :iso_two_letter_code => 'EG' },
  { :title => 'El Salvador', :iso_two_letter_code => 'SV' },
  { :title => 'Equatorial Guinea', :iso_two_letter_code => 'GQ' },
  { :title => 'Eritrea', :iso_two_letter_code => 'ER' },
  { :title => 'Estonia', :iso_two_letter_code => 'EE' },
  { :title => 'Ethiopia', :iso_two_letter_code => 'ET' },
  { :title => 'Falkland Islands', :iso_two_letter_code => 'FK' },
  { :title => 'Faroe Islands', :iso_two_letter_code => 'FO' },
  { :title => 'Fiji', :iso_two_letter_code => 'FJ' },
  { :title => 'Finland', :iso_two_letter_code => 'FI' },
  { :title => 'France', :iso_two_letter_code => 'FR' },
  { :title => 'French Guiana', :iso_two_letter_code => 'GF' },
  { :title => 'French Polynesia', :iso_two_letter_code => 'PF' },
  { :title => 'French Southern Territories', :iso_two_letter_code => 'TF' },
  { :title => 'Gabon', :iso_two_letter_code => 'GA' },
  { :title => 'Gambia', :iso_two_letter_code => 'GM' },
  { :title => 'Georgia', :iso_two_letter_code => 'GE' },
  { :title => 'Germany', :iso_two_letter_code => 'DE' },
  { :title => 'Ghana', :iso_two_letter_code => 'GH' },
  { :title => 'Gibraltar', :iso_two_letter_code => 'GI' },
  { :title => 'Greece', :iso_two_letter_code => 'GR' },
  { :title => 'Greenland', :iso_two_letter_code => 'GL' },
  { :title => 'Grenada', :iso_two_letter_code => 'GD' },
  { :title => 'Guadeloupe', :iso_two_letter_code => 'GP' },
  { :title => 'Guam', :iso_two_letter_code => 'GU' },
  { :title => 'Guatemala', :iso_two_letter_code => 'GT' },
  { :title => 'Guernsey', :iso_two_letter_code => 'GG' },
  { :title => 'Guinea', :iso_two_letter_code => 'GN' },
  { :title => 'Guinea-Bissau', :iso_two_letter_code => 'GW' },
  { :title => 'Guyana', :iso_two_letter_code => 'GY' },
  { :title => 'Haiti', :iso_two_letter_code => 'HT' },
  { :title => 'Heard and McDonald Islands', :iso_two_letter_code => 'HM' },
  { :title => 'Holy See (Vatican City State)', :iso_two_letter_code => 'VA' },
  { :title => 'Honduras', :iso_two_letter_code => 'HN' },
  { :title => 'Hong Kong', :iso_two_letter_code => 'HK' },
  { :title => 'Hungary', :iso_two_letter_code => 'HU' },
  { :title => 'Iceland', :iso_two_letter_code => 'IS' },
  { :title => 'India', :iso_two_letter_code => 'IN' },
  { :title => 'Indonesia', :iso_two_letter_code => 'ID' },
  { :title => 'Iran', :iso_two_letter_code => 'IR' },
  { :title => 'Iraq', :iso_two_letter_code => 'IQ' },
  { :title => 'Ireland', :iso_two_letter_code => 'IE' },
  { :title => 'Isle of Man', :iso_two_letter_code => 'IM' },
  { :title => 'Israel', :iso_two_letter_code => 'IL' },
  { :title => 'Italy', :iso_two_letter_code => 'IT' },
  { :title => 'Jamaica', :iso_two_letter_code => 'JM' },
  { :title => 'Japan', :iso_two_letter_code => 'JP' },
  { :title => 'Jersey', :iso_two_letter_code => 'JE' },
  { :title => 'Jordan', :iso_two_letter_code => 'JO' },
  { :title => 'Kazakhstan', :iso_two_letter_code => 'KZ' },
  { :title => 'Kenya', :iso_two_letter_code => 'KE' },
  { :title => 'Kiribati', :iso_two_letter_code => 'KI' },
  { :title => 'North Korea', :iso_two_letter_code => 'KP' },
  { :title => 'South Korea', :iso_two_letter_code => 'KR' },
  { :title => 'Kuwait', :iso_two_letter_code => 'KW' },
  { :title => 'Kyrgyzstan', :iso_two_letter_code => 'KG' },
  { :title => 'Laos', :iso_two_letter_code => 'LA' },
  { :title => 'Latvia', :iso_two_letter_code => 'LV' },
  { :title => 'Lebanon', :iso_two_letter_code => 'LB' },
  { :title => 'Lesotho', :iso_two_letter_code => 'LS' },
  { :title => 'Liberia', :iso_two_letter_code => 'LR' },
  { :title => 'Libya', :iso_two_letter_code => 'LY' },
  { :title => 'Liechtenstein', :iso_two_letter_code => 'LI' },
  { :title => 'Lithuania', :iso_two_letter_code => 'LT' },
  { :title => 'Luxembourg', :iso_two_letter_code => 'LU' },
  { :title => 'Macao', :iso_two_letter_code => 'MO' },
  { :title => 'Macedonia', :iso_two_letter_code => 'MK' },
  { :title => 'Madagascar', :iso_two_letter_code => 'MG' },
  { :title => 'Malawi', :iso_two_letter_code => 'MW' },
  { :title => 'Malaysia', :iso_two_letter_code => 'MY' },
  { :title => 'Maldives', :iso_two_letter_code => 'MV' },
  { :title => 'Mali', :iso_two_letter_code => 'ML' },
  { :title => 'Malta', :iso_two_letter_code => 'MT' },
  { :title => 'Marshall Islands', :iso_two_letter_code => 'MH' },
  { :title => 'Martinique', :iso_two_letter_code => 'MQ' },
  { :title => 'Mauritania', :iso_two_letter_code => 'MR' },
  { :title => 'Mauritius', :iso_two_letter_code => 'MU' },
  { :title => 'Mayotte', :iso_two_letter_code => 'YT' },
  { :title => 'Mexico', :iso_two_letter_code => 'MX' },
  { :title => 'Micronesia', :iso_two_letter_code => 'FM' },
  { :title => 'Moldova', :iso_two_letter_code => 'MD' },
  { :title => 'Monaco', :iso_two_letter_code => 'MC' },
  { :title => 'Mongolia', :iso_two_letter_code => 'MN' },
  { :title => 'Montenegro', :iso_two_letter_code => 'ME' },
  { :title => 'Montserrat', :iso_two_letter_code => 'MS' },
  { :title => 'Morocco', :iso_two_letter_code => 'MA' },
  { :title => 'Mozambique', :iso_two_letter_code => 'MZ' },
  { :title => 'Myanmar', :iso_two_letter_code => 'MM' },
  { :title => 'Namibia', :iso_two_letter_code => 'NA' },
  { :title => 'Nauru', :iso_two_letter_code => 'NR' },
  { :title => 'Nepal', :iso_two_letter_code => 'NP' },
  { :title => 'Netherlands', :iso_two_letter_code => 'NL' },
  { :title => 'Netherlands Antilles', :iso_two_letter_code => 'AN' },
  { :title => 'New Caledonia', :iso_two_letter_code => 'NC' },
  { :title => 'New Zealand', :iso_two_letter_code => 'NZ' },
  { :title => 'Nicaragua', :iso_two_letter_code => 'NI' },
  { :title => 'Niger', :iso_two_letter_code => 'NE' },
  { :title => 'Nigeria', :iso_two_letter_code => 'NG' },
  { :title => 'Niue', :iso_two_letter_code => 'NU' },
  { :title => 'Norfolk Island', :iso_two_letter_code => 'NF' },
  { :title => 'Northern Mariana Islands', :iso_two_letter_code => 'MP' },
  { :title => 'Norway', :iso_two_letter_code => 'NO' },
  { :title => 'Oman', :iso_two_letter_code => 'OM' },
  { :title => 'Pakistan', :iso_two_letter_code => 'PK' },
  { :title => 'Palau', :iso_two_letter_code => 'PW' },
  { :title => 'Palestinian Territory', :iso_two_letter_code => 'PS' },
  { :title => 'Panama', :iso_two_letter_code => 'PA' },
  { :title => 'Papua New Guinea', :iso_two_letter_code => 'PG' },
  { :title => 'Paraguay', :iso_two_letter_code => 'PY' },
  { :title => 'Peru', :iso_two_letter_code => 'PE' },
  { :title => 'Philippines', :iso_two_letter_code => 'PH' },
  { :title => 'Pitcairn', :iso_two_letter_code => 'PN' },
  { :title => 'Poland', :iso_two_letter_code => 'PL' },
  { :title => 'Portugal', :iso_two_letter_code => 'PT' },
  { :title => 'Puerto Rico', :iso_two_letter_code => 'PR' },
  { :title => 'Qatar', :iso_two_letter_code => 'QA' },
  { :title => 'Reunion', :iso_two_letter_code => 'RE' },
  { :title => 'Romania', :iso_two_letter_code => 'RO' },
  { :title => 'Rwanda', :iso_two_letter_code => 'RW' },
  { :title => 'Saint Barthelemy', :iso_two_letter_code => 'BL' },
  { :title => 'Saint Helena', :iso_two_letter_code => 'SH' },
  { :title => 'Saint Kitts and Nevis', :iso_two_letter_code => 'KN' },
  { :title => 'Saint Lucia', :iso_two_letter_code => 'LC' },
  { :title => 'Saint Pierre and Miquelon', :iso_two_letter_code => 'PM' },
  { :title => 'Saint Vincent and the Grenadines', :iso_two_letter_code => 'VC' },
  { :title => 'Samoa', :iso_two_letter_code => 'WS' },
  { :title => 'San Marino', :iso_two_letter_code => 'SM' },
  { :title => 'Sao Tome and Principe', :iso_two_letter_code => 'ST' },
  { :title => 'Saudi Arabia', :iso_two_letter_code => 'SA' },
  { :title => 'Senegal', :iso_two_letter_code => 'SN' },
  { :title => 'Serbia', :iso_two_letter_code => 'RS' },
  { :title => 'Seychelles', :iso_two_letter_code => 'SC' },
  { :title => 'Sierra Leone', :iso_two_letter_code => 'SL' },
  { :title => 'Singapore', :iso_two_letter_code => 'SG' },
  { :title => 'Slovakia', :iso_two_letter_code => 'SK' },
  { :title => 'Slovenia', :iso_two_letter_code => 'SI' },
  { :title => 'Solomon Islands', :iso_two_letter_code => 'SB' },
  { :title => 'Somalia', :iso_two_letter_code => 'SO' },
  { :title => 'South Africa', :iso_two_letter_code => 'ZA' },
  { :title => 'South Georgia and the South Sandwich Islands', :iso_two_letter_code => 'GS' },
  { :title => 'Spain', :iso_two_letter_code => 'ES' },
  { :title => 'Sri Lanka', :iso_two_letter_code => 'LK' },
  { :title => 'Sudan', :iso_two_letter_code => 'SD' },
  { :title => 'Surinam', :iso_two_letter_code => 'SR' },
  { :title => 'Svalbard and Jan Mayen', :iso_two_letter_code => 'SJ' },
  { :title => 'Swaziland', :iso_two_letter_code => 'SZ' },
  { :title => 'Sweden', :iso_two_letter_code => 'SE' },
  { :title => 'Switzerland', :iso_two_letter_code => 'CH' },
  { :title => 'Syria', :iso_two_letter_code => 'SY' },
  { :title => 'Taiwan', :iso_two_letter_code => 'TW' },
  { :title => 'Tajikistan', :iso_two_letter_code => 'TJ' },
  { :title => 'Tanzania', :iso_two_letter_code => 'TZ' },
  { :title => 'Thailand', :iso_two_letter_code => 'TH' },
  { :title => 'Timor-Leste', :iso_two_letter_code => 'TL' },
  { :title => 'Togo', :iso_two_letter_code => 'TG' },
  { :title => 'Tokelau', :iso_two_letter_code => 'TK' },
  { :title => 'Tonga', :iso_two_letter_code => 'TO' },
  { :title => 'Trinidad and Tobago', :iso_two_letter_code => 'TT' },
  { :title => 'Tunisia', :iso_two_letter_code => 'TN' },
  { :title => 'Turkey', :iso_two_letter_code => 'TR' },
  { :title => 'Turkmenistan', :iso_two_letter_code => 'TM' },
  { :title => 'Turks and Caicos Islands', :iso_two_letter_code => 'TC' },
  { :title => 'Tuvalu', :iso_two_letter_code => 'TV' },
  { :title => 'Uganda', :iso_two_letter_code => 'UG' },
  { :title => 'UAE', :iso_two_letter_code => 'AE' },
  { :title => 'United States Minor Outlying Islands', :iso_two_letter_code => 'UM' },
  { :title => 'Uruguay', :iso_two_letter_code => 'UY' },
  { :title => 'Uzbekistan', :iso_two_letter_code => 'UZ' },
  { :title => 'Vanuatu', :iso_two_letter_code => 'VU' },
  { :title => 'Venezuela', :iso_two_letter_code => 'VE' },
  { :title => 'Vietnam', :iso_two_letter_code => 'VN' },
  { :title => 'British Virgin Islands', :iso_two_letter_code => 'VG' },
  { :title => 'US Virgin Islands', :iso_two_letter_code => 'VI' },
  { :title => 'Wallis and Futuna', :iso_two_letter_code => 'WF' },
  { :title => 'Western Sahara', :iso_two_letter_code => 'EH' },
  { :title => 'Yemen', :iso_two_letter_code => 'YE' },
  { :title => 'Zambia', :iso_two_letter_code => 'ZM' },
  { :title => 'Zimbabwe', :iso_two_letter_code => 'ZW' }  
].each do |c|
  Country.find_or_create_by_title(:title => c[:title], :iso_two_letter_code => c[:iso_two_letter_code])
end
